### ISSUE TITLE
50 stars lol

### ISSUE THREAD

**Issue by Mewzax** [Imagine-YT/Discord-Token-Generator#3]

**Comment by 1x6** [comment]
fr

**Comment by 1x6** [comment]
its prob cap

**Comment by 9tro** [comment]
ion think he can code at all. he can't even compile pirate lmao

**Comment by 1x6** [comment]
LOOOOOOOOOOL

**Comment by 1x6** [comment]
good on you man, doing ur research like fr

**Comment by 9tro** [comment]
![image](https://user-images.githubusercontent.com/77902240/170084076-4de6f04e-eefa-42ea-8c5a-465d8e6be821.png)

🤷

**Comment by 9tro** [comment]
@Imagine-YT where'd you get the gen from? you made it or did someone else make it?
